services:
  postgres:
    image: postgres:16-alpine
    container_name: jogolimpo-db
    environment:
      POSTGRES_USER: jogolimpo
      POSTGRES_PASSWORD: jogolimpo
      POSTGRES_DB: jogolimpo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
